### ISSUE TITLE
Poprawność kodu

### ISSUE THREAD

**Issue by efiku** [kreex/tld#1]
Hej.
Dam Ci parę wskazówek dotyczących kodu. 
Mam chwilę czasu więc... 

Struktura katalogów:
Poniżej pokażę Ci przykładową strukturę katalogów jak wygląda to w PHP i jakiej pasowałoby się trzymać:
```
./
├── src (1)
├── vendor (2)
│   └── Paczki od innych programistów
├── composer.json
└── web (3)
    ├── index.php
    └── pliczki
```
**(1)** - tutaj kod PHP, gdy przepiszesz na OOP to zrozumiesz :)
**(2)** - tutaj zazwyczaj trzymane są biblioteki np. Doctrine
**(3)** - tutaj jest jeden plik php zazwyczaj index.php który otrzymuje requesty i zwraca respnse. Kod PHP powinien być wyżej niż katalog root strony. Także index.php nie jest niczym innym jak pośrednikiem
**composer.json**→ Manager paczek, który sprawi, że Twoje życie jako programisty będzie na czasie i szczęśliwsze.

_____

##  Zacznijmy od mieszania PHP z HTML.
Wielokrotnie tłumaczyliśmy, aby zainteresować się twigiem. Szybki i profesjonalny system szablonów.
Oddzielenie kodu od widoku to ukłon w stronę zarówno programistów backendu jak i frontendu ;)
Oraz +1 do czytelności kodu.

## Mysqli i małpa
Małpa Ci nie potrzeba, to bardzo zły nawyk. Polecam poczytać jak przygotować środowisko PHP do pracy, bo na produkcji błędy i tak masz wyłączone, zaś na dev środowisku - wskazane je mieć włączone.

Pierwszym krokiem do zmiany będzie dostosowanie kodu do katalogów które Ci podałem, później pałeczkę przejmie Composer, zajmie się on autoloadingiem Twoich funkcji. 
Kolejnym krokiem będzie zassanie doctrine.
Mysqli to tandetne ... gówno. Stosowane co najwyżej na kursach ;)
ORM i DBAL.
(Warto poczytać o czym piszę)
A jak to za ciężko, to chociaż samo [PDO](https://gist.github.com/efiku/1d9a562b3a47edee3681):

## dbconnect
ładujesz wszędzie, ale po co? Przerzuć konfigurację na ymle. :) 

## REQUEST
Spoko, jest request, ale brak sprawdzania, gdybym się odwołał normalnie z poziomu strony do tego pliku "GET" to bym dostał masę noticów, a Twój skrypt wywołałby spore zamieszanie.. Poczytaj co siedzi w _REQUEST ;)

Polecam zassać composerem komponent HttpFoundation od symfony!

## Zapytania do bazy
[Nie używaj SELECT * ](http://www.sqlinsider.pl/2015/03/7-powodow-dlaczego-nie-powinno-sie.html)tylko konkretnie się dowołuj do kolumn. ;)
Nie używasz "Prepared Statements" (Polecam PDO i googluj za tym)
Filtruj dane!

##  Podsumowanie: Kod 
- Jest aplikacja, niby działa, ale kod jest średni, nie poddawaj się tylko udoskonalaj ten projekt. -
- Brak testów jednostkowych. -
- brak compsoera -
+ Za nie stosowanie globali w funkcjach, gdyż jest to zła praktyka +
+ Po cichu w funkcji DBQuery czy jak jej tam, stosujesz miły dla oka wzorzec Dependency Injection. +
- Brak Ci wiedzy na temat PSR -
+ Starasz się rozbić pliki niż pchać wszystko do jednego +
- Powtarzasz kod  -
- do obsługi tablic stosujemy [foreach](https://php-kurs.gitbooks.io/phpkurs/content/czesc-i/tablice.html), nie for :)  -
- do require ( ) nie musisz nawiasów, ba ! Możesz przekazać zawartość innego pliku php :) +/- 
- nie musisz zamykać tagiem ?>, jeśli nie mieszasz z HTML ;) 
```php
<?php
# plik_1.php
return [ 
  "tablica" => "smieszki"
];
```
```php
<?php
# plik_2.php
$tablica = require "plik_1.php";
var_dump($tablica);
```

Ważny link: 
https://symfony.com/doc/current/book/http_fundamentals.html
https://php-kurs.gitbooks.io/phpkurs/content/czesc-v/pisanie-stron-obiektowo.html

**Comment by kreex** [comment]
Wielkie dzięki za taką dokładniejszą analizę. Będzie to dla mnie dobry punkt wyjścia
